window.leadGenerator = window.leadGenerator || {};

if (!window.leadGenerator.companyLabelsInit) {
  // Overview field labels on a company's About page, per LinkedIn interface
  // language (LinkedIn shows them in the language set in the user's profile).
  // `members` holds a word stem of the "N associated members" link text, so
  // it matches every grammatical form. Matching ignores letter case and the
  // apostrophe style. Add a variant here if a language's data comes back empty.
  window.leadGenerator.companyLabels = {
    ar: {
      website: ["الموقع الإلكتروني", "الموقع الالكتروني"],
      industry: ["المجال", "الصناعة", "القطاع"],
      size: ["حجم الشركة"],
      headquarters: ["المقر الرئيسي", "المقر"],
      members: ["عضو", "أعضاء"],
    },
    bn: {
      website: ["ওয়েবসাইট"],
      industry: ["শিল্প", "ইন্ডাস্ট্রি"],
      size: ["কোম্পানির আকার"],
      headquarters: ["সদর দপ্তর", "সদরদপ্তর"],
      members: ["সদস্য"],
    },
    cs: {
      website: ["Webové stránky", "Web"],
      industry: ["Odvětví", "Obor"],
      size: ["Velikost společnosti", "Velikost firmy"],
      headquarters: ["Sídlo", "Ústředí"],
      members: ["člen"],
    },
    da: {
      website: ["Websted", "Website", "Hjemmeside"],
      industry: ["Branche"],
      size: ["Virksomhedsstørrelse", "Virksomhedens størrelse"],
      headquarters: ["Hovedkvarter", "Hovedkontor"],
      members: ["medlem"],
    },
    de: {
      website: ["Website", "Webseite"],
      industry: ["Branche"],
      size: ["Unternehmensgröße", "Größe"],
      headquarters: ["Hauptsitz", "Zentrale"],
      members: ["mitglied"],
    },
    el: {
      website: ["Ιστότοπος", "Ιστοσελίδα"],
      industry: ["Κλάδος", "Βιομηχανία"],
      size: ["Μέγεθος εταιρείας", "Μέγεθος εταιρίας"],
      headquarters: ["Έδρα", "Κεντρικά γραφεία"],
      members: ["μέλ"],
    },
    en: {
      website: ["Website"],
      industry: ["Industry"],
      size: ["Company size"],
      headquarters: ["Headquarters"],
      members: ["associated member"],
    },
    es: {
      website: ["Sitio web"],
      industry: ["Sector"],
      size: ["Tamaño de la empresa"],
      headquarters: ["Sede", "Sede central"],
      members: ["miembro"],
    },
    fa: {
      website: ["وب‌سایت", "وبسایت", "وب سایت"],
      industry: ["صنعت"],
      size: ["اندازه شرکت", "اندازه‌ شرکت"],
      headquarters: ["دفتر مرکزی", "مقر اصلی"],
      members: ["عضو"],
    },
    fi: {
      website: ["Verkkosivusto", "Verkkosivut"],
      industry: ["Toimiala"],
      size: ["Yrityksen koko"],
      headquarters: ["Pääkonttori", "Päätoimipaikka"],
      members: ["jäsen"],
    },
    fr: {
      website: ["Site web", "Site Web"],
      industry: ["Secteur", "Secteur d'activité"],
      size: ["Taille de l'entreprise"],
      headquarters: ["Siège social", "Siège"],
      members: ["membre"],
    },
    he: {
      website: ["אתר אינטרנט", "אתר"],
      industry: ["תעשייה", "ענף"],
      size: ["גודל החברה"],
      headquarters: ["מטה", "המטה"],
      members: ["חבר"],
    },
    hi: {
      website: ["वेबसाइट"],
      industry: ["उद्योग"],
      size: ["कंपनी का आकार", "कंपनी आकार"],
      headquarters: ["मुख्यालय"],
      members: ["सदस्य"],
    },
    hu: {
      website: ["Webhely", "Weboldal"],
      industry: ["Iparág", "Ágazat"],
      size: ["Cégméret", "Vállalat mérete"],
      headquarters: ["Székhely", "Központ"],
      members: ["tag"],
    },
    id: {
      website: ["Situs web", "Situs Web"],
      industry: ["Industri"],
      size: ["Ukuran perusahaan"],
      headquarters: ["Kantor pusat", "Kantor Pusat"],
      members: ["anggota"],
    },
    it: {
      website: ["Sito web", "Sito Web"],
      industry: ["Settore"],
      size: ["Dimensioni dell'azienda", "Dimensione dell'azienda"],
      headquarters: ["Sede principale", "Sede centrale", "Sede"],
      members: ["membr"],
    },
    ja: {
      website: ["ウェブサイト", "Webサイト"],
      industry: ["業種", "業界"],
      size: ["会社規模", "従業員数"],
      headquarters: ["本社", "本社所在地"],
      members: ["メンバー"],
    },
    ko: {
      website: ["웹사이트"],
      industry: ["업계", "업종", "산업"],
      size: ["회사 규모"],
      headquarters: ["본사"],
      members: ["회원", "멤버"],
    },
    mr: {
      website: ["वेबसाइट"],
      industry: ["उद्योग"],
      size: ["कंपनीचा आकार", "कंपनी आकार"],
      headquarters: ["मुख्यालय"],
      members: ["सदस्य"],
    },
    ms: {
      website: ["Laman web", "Laman Web", "Tapak web"],
      industry: ["Industri"],
      size: ["Saiz syarikat", "Saiz Syarikat"],
      headquarters: ["Ibu pejabat", "Ibu Pejabat"],
      members: ["ahli"],
    },
    nl: {
      website: ["Website"],
      industry: ["Branche", "Sector"],
      size: ["Bedrijfsgrootte"],
      headquarters: ["Hoofdkantoor"],
      members: ["leden"],
    },
    no: {
      website: ["Nettsted", "Nettside"],
      industry: ["Bransje"],
      size: ["Bedriftsstørrelse", "Selskapsstørrelse"],
      headquarters: ["Hovedkontor"],
      members: ["medlem"],
    },
    pa: {
      website: ["ਵੈੱਬਸਾਈਟ", "ਵੈਬਸਾਈਟ"],
      industry: ["ਉਦਯੋਗ"],
      size: ["ਕੰਪਨੀ ਦਾ ਆਕਾਰ"],
      headquarters: ["ਮੁੱਖ ਦਫ਼ਤਰ", "ਮੁੱਖ ਦਫਤਰ", "ਹੈੱਡਕੁਆਰਟਰ"],
      members: ["ਮੈਂਬਰ", "ਸਦੱਸ"],
    },
    pl: {
      website: ["Witryna internetowa", "Strona internetowa", "Witryna"],
      industry: ["Branża"],
      size: ["Wielkość firmy", "Rozmiar firmy"],
      headquarters: ["Siedziba główna", "Siedziba"],
      members: ["członk"],
    },
    pt: {
      website: ["Site", "Website", "Sítio web"],
      industry: ["Setor"],
      size: ["Tamanho da empresa"],
      headquarters: ["Sede"],
      members: ["membro"],
    },
    ro: {
      website: ["Site web", "Site"],
      industry: ["Domeniu", "Industrie", "Sector"],
      size: ["Dimensiunea companiei", "Mărimea companiei"],
      headquarters: ["Sediu central", "Sediul central", "Sediu"],
      members: ["membr"],
    },
    ru: {
      website: ["Сайт", "Веб-сайт", "Вебсайт"],
      industry: ["Отрасль"],
      size: ["Размер компании"],
      headquarters: ["Штаб-квартира", "Головной офис"],
      members: ["участник"],
    },
    sv: {
      website: ["Webbplats", "Webbsida"],
      industry: ["Bransch"],
      size: ["Företagsstorlek"],
      headquarters: ["Huvudkontor", "Huvudsäte"],
      members: ["medlem"],
    },
    te: {
      website: ["వెబ్‌సైట్", "వెబ్సైట్"],
      industry: ["పరిశ్రమ"],
      size: ["కంపెనీ పరిమాణం"],
      headquarters: ["ప్రధాన కార్యాలయం"],
      members: ["సభ్య"],
    },
    th: {
      website: ["เว็บไซต์"],
      industry: ["อุตสาหกรรม"],
      size: ["ขนาดบริษัท", "ขนาดของบริษัท"],
      headquarters: ["สำนักงานใหญ่"],
      members: ["สมาชิก"],
    },
    tl: {
      website: ["Website"],
      industry: ["Industriya", "Industry"],
      size: ["Laki ng kompanya", "Laki ng kumpanya"],
      headquarters: ["Punong-tanggapan", "Punong tanggapan", "Headquarters"],
      members: ["miyembro"],
    },
    tr: {
      website: ["Web sitesi"],
      industry: ["Sektör"],
      size: ["Şirket büyüklüğü", "Şirket boyutu"],
      headquarters: ["Genel Merkez", "Merkez"],
      members: ["üye"],
    },
    uk: {
      website: ["Вебсайт", "Веб-сайт", "Сайт"],
      industry: ["Галузь"],
      size: ["Розмір компанії"],
      headquarters: ["Штаб-квартира", "Головний офіс"],
      members: ["учасник", "член"],
    },
    vi: {
      website: ["Trang web"],
      industry: ["Ngành", "Ngành nghề"],
      size: ["Quy mô công ty"],
      headquarters: ["Trụ sở chính", "Trụ sở"],
      members: ["thành viên"],
    },
    "zh-CN": {
      website: ["网站"],
      industry: ["行业", "领域"],
      size: ["公司规模"],
      headquarters: ["总部"],
      members: ["成员", "会员"],
    },
    "zh-TW": {
      website: ["網站"],
      industry: ["產業", "行業"],
      size: ["公司規模"],
      headquarters: ["總部"],
      members: ["成員", "會員"],
    },
  };

  window.leadGenerator.companyLabelsInit = true;
}
